#! usr/bin/env php
<?php

namespace Behavioral\Observer;

require_once 'vendor/autoload.php';

$team = new FootballSubject('Manchester United');

try {
    $team->attachObserver(new FootballObserver('John'));
    $team->attachObserver(new FootballObserver('Bill'));

    $team->notify(new FootballEvent(FootballEvent::GOAL));
    $team->notify(new FootballEvent(FootballEvent::MISS));
    $team->notify(new FootballEvent(FootballEvent::CARD));

    $team->detachObserver('Bill');
    $team->attachObserver(new FootballObserver('Steve'));

    $team->notify(new FootballEvent(FootballEvent::GOAL));
    $team->notify(new FootballEvent('Offside'));
} catch (\Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}

